Resources:
  # SQS Queue to process Color Map entries
  ColorMapsProcessingQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 300
      ReceiveMessageWaitTimeSeconds: 20

  TagProcessingQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 300
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - TagProcessingDeadLetterQueue
            - Arn
        maxReceiveCount: 2 # Number of times a message will be tried before being dumped to the DLQ

  TagProcessingDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.siteName}-TagProcessingDeadLetterQueue
      MessageRetentionPeriod: 1209600

  CmrOrderingOrderQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 600
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - CmrOrderingOrderDeadLetterQueue
            - Arn
        maxReceiveCount: 2 # Number of times a message will be tried before being dumped to the DLQ

  CmrOrderingOrderDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.siteName}-CmrOrderingOrderDeadLetterQueue
      MessageRetentionPeriod: 1209600

  CatalogRestOrderQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 600 # Give orders a full day to complete
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - CatalogRestOrderDeadLetterQueue
            - Arn
        maxReceiveCount: 2 # Number of times a message will be tried before being dumped to the DLQ

  CatalogRestOrderDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.siteName}-CatalogRestOrderDeadLetterQueue
      MessageRetentionPeriod: 1209600

  HarmonyOrderQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 600 # Give orders a full day to complete
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - HarmonyOrderDeadLetterQueue
            - Arn
        maxReceiveCount: 2 # Number of times a message will be tried before being dumped to the DLQ

  HarmonyOrderDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.siteName}-HarmonyOrderDeadLetterQueue
      MessageRetentionPeriod: 1209600
  
  SwodlrOrderQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 600 # Give orders a full day to complete
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - SwodlrOrderDeadLetterQueue
            - Arn
        maxReceiveCount: 2 # Number of times a message will be tried before being dumped to the DLQ

  SwodlrOrderDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.siteName}-SwodlrOrderDeadLetterQueue
      MessageRetentionPeriod: 1209600

  OrderStatusQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 300

  UserDataQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - UserDataQueueDeadLetterQueue
            - Arn
        maxReceiveCount: 2 # Number of times a message will be tried before being dumped to the DLQ

  UserDataQueueDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.siteName}-UserDataQueueDeadLetterQueue
      MessageRetentionPeriod: 1209600

  GatewayResponseDefault4XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_4XX
      RestApiId:
        Ref: ApiGatewayRestApi

  GatewayResponseDefault5XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_5XX
      RestApiId:
        Ref: ApiGatewayRestApi

  # This role must not be changed -- if it is removed Serverless will attempt to automatically
  # recreate it and deployments will fail because our permissions boundary does not allow for
  # creation of roles. This role is used specifically for S3 Lambda triggers that use existing
  # buckets, which is what we're using for forwarding cloudfront logs to Splunk.
  IamRoleCustomResourcesLambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      PermissionsBoundary:
        Fn::Join: [
          "", [
            "arn:aws:iam::",
            {
              "Ref": "AWS::AccountId"
            },
            ":policy/${self:custom.variables.boundaryPolicy}"
          ]
        ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole

  S3CloudfrontLogToCloudwatchPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "s3:GetBucketLocation"
              - "s3:ListBucket"
              - "s3:ListAllMyBuckets"
              - "s3:GetObject"
            Effect: "Allow"
            Resource: "*"
      PolicyName: ${self:provider.stage}-S3CloudfrontLogToCloudwatchPolicy
      Roles:
        - Ref: IamRoleCustomResourcesLambdaExecution

  ApiGatewayRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: ${self:provider.stage}-EarthDataSearchApiGatewayRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                Resource:
                  - !Sub "arn:aws:s3:::${env:CLOUDFRONT_BUCKET_NAME, ''}/*"

  ApiGatewayMethodForS3Index:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: GET
      MethodResponses:
        - StatusCode: 200
          # ResponseModels: {"text/html": "Empty"}
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Timestamp: true
      ResourceId: !GetAtt ApiGatewayRestApi.RootResourceId
      RestApiId: !Ref ApiGatewayRestApi
      AuthorizationType: NONE
      Integration:
        Type: AWS
        Credentials: !GetAtt ApiGatewayRole.Arn
        IntegrationHttpMethod: GET
        Uri: !Sub "arn:${AWS::Partition}:apigateway:${AWS::Region}:s3:path/${env:CLOUDFRONT_BUCKET_NAME, ''}/index.html"
        PassthroughBehavior: WHEN_NO_TEMPLATES
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters: {"method.response.header.Content-Type": "integration.response.header.Content-Type", "method.response.header.Timestamp": "integration.response.header.Date"}

  AssetsResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: 'assets'

  ProxyResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !Ref AssetsResource
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: '{proxy+}'

  ApiGatewayMethodForS3Assets:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: GET
      ResourceId: !Ref ProxyResource
      RestApiId: !Ref ApiGatewayRestApi
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.proxy: true
      Integration:
        CacheKeyParameters:
          - 'method.request.path.proxy'
        RequestParameters:
          integration.request.path.proxy: 'method.request.path.proxy'
        Type: AWS
        Credentials: !GetAtt ApiGatewayRole.Arn
        IntegrationHttpMethod: GET
        Uri: !Sub "arn:${AWS::Partition}:apigateway:${AWS::Region}:s3:path/${env:CLOUDFRONT_BUCKET_NAME, ''}/assets/{proxy}"
        PassthroughBehavior: WHEN_NO_TEMPLATES
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters: {"method.response.header.Content-Type": "integration.response.header.Content-Type", "method.response.header.Timestamp": "integration.response.header.Date"}
      MethodResponses:
        - StatusCode: 200
          ResponseModels: {"text/javascript": "Empty", "text/html": "Empty", "image/png": "Empty", "text/css": "Empty"}
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Timestamp: true

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
     - ApiGatewayMethodForS3Index
     - ApiGatewayMethodForS3Assets
    Properties:
      Description: API Gateway for Earth Data Search ${self:provider.stage}
      RestApiId: !Ref ApiGatewayRestApi
      StageName: dev
      # StageDescription:

  CloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE]
          ForwardedValues:
            QueryString: false
          TargetOriginId: dev
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - Id: dev
            DomainName: !Sub
              - ${api}.execute-api.${AWS::Region}.amazonaws.com
              - api: !Ref ApiGatewayRestApi
            OriginPath: /dev
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [TLSv1.2]



Outputs:
  UpdateOrderStatusWorkflow:
    Description: ARN of the order status step function workflow
    Value:
      Ref: UpdateOrderStatusWorkflowDash${self:provider.stage}
